// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/","redirect":"/film","parentId":"@@/global-layout","id":"1"},"2":{"path":"/film","redirect":"/film/nowplaying","parentId":"@@/global-layout","id":"2"},"3":{"path":"","file":"@/pages/center.tsx","parentId":"4","id":"3","originPath":"/center"},"4":{"path":"/center","isWrapper":true,"file":"@/wrappers/auth.tsx","parentId":"@@/global-layout","id":"4"},"5":{"path":"/cinma","file":"@/pages/cinma.tsx","parentId":"@@/global-layout","id":"5"},"6":{"path":"/detail/:myid","file":"@/pages/detail.tsx","parentId":"@@/global-layout","id":"6"},"7":{"path":"/login","file":"@/pages/login.tsx","parentId":"@@/global-layout","id":"7"},"8":{"path":"/city","file":"@/pages/city.tsx","parentId":"@@/global-layout","id":"8"},"9":{"path":"/","file":"@/pages/film.tsx","parentId":"@@/global-layout","id":"9"},"10":{"path":"film/nowplaying","file":"@/pages/film/nowPlaying.tsx","parentId":"9","id":"10"},"11":{"path":"film/comingsoon","file":"@/pages/film/comingsoon.tsx","parentId":"9","id":"11"},"@@/global-layout":{"id":"@@/global-layout","path":"/","file":"@/layouts/index.tsx","isLayout":true}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import( './EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__center" */'@/pages/center.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "wrappers__auth" */'@/wrappers/auth.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__cinma" */'@/pages/cinma.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__detail" */'@/pages/detail.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__login" */'@/pages/login.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__city" */'@/pages/city.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__film" */'@/pages/film.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__film__nowPlaying" */'@/pages/film/nowPlaying.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__film__comingsoon" */'@/pages/film/comingsoon.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'@/layouts/index.tsx')),
},
  };
}
