// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/web_learing/React框架/教程版/umiapp/src/models/cinemaModel';
import model_2 from 'D:/web_learing/React框架/教程版/umiapp/src/models/count';

export const models = {
model_1: { namespace: 'cinemaModel', model: model_1 },
model_2: { namespace: 'count', model: model_2 },
} as const
