// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/web_learing/React框架/教程版/umiapp/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/web_learing/React框架/教程版/umiapp/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// plugins
export { connect, useDispatch, useStore, useSelector, getDvaApp } from 'D:/web_learing/React框架/教程版/umiapp/src/.umi/plugin-dva';
// plugins types.d.ts
export { defineApp } from './core/defineApp'
export type {  RuntimeConfig } from './core/defineApp'
